sudo: required

services: docker

git: { depth: 1 }

env:
    global:
        - DOCKER_IMAGE="rindeal/portage-amd64-base"
        - DOCKER_TAG="latest"

install:
    - 'docker pull "${DOCKER_IMAGE}:${DOCKER_TAG}"'

script:
    - 'docker run --privileged -v $PWD:/repo:ro "${DOCKER_IMAGE}:${DOCKER_TAG}" /repo/ci'
