#!/bin/bash

set -o pipefail
set -ue

export RINDEAL_DEBUG=1

PKG="$( EIX_LIMIT=0 eix --in-overlay rindeal --only-names | shuf -n1 )"
echo
echo -e "\e[36mTesting '\e[1m$PKG\e[21m'\e[0m"
echo

emerge=(
    env CONFIG_PROTECT= emerge --verbose-conflicts --verbose --jobs=4 --load-average=4 --autounmask-write y --quiet n --quiet-build y --quiet-fail n "${PKG}"
)
echo "${emerge[@]}"
"${emerge[@]}"
